import type { ElementType } from 'react';
import {
  Dashboard, Palette, TextFields, SpaceBar, Gradient, Layers,
  CropSquare, Animation, Widgets, Visibility, DesktopWindows,
  Search, ShoppingCart, BarChart, Menu, Close, Notifications,
  AccountCircle, Settings, Home, Mail, Phone, Favorite,
  Share, Bookmark, Edit, Delete, Add, Remove, Check,
  Warning, Info, Error, CheckCircle,
  ArrowForward, ArrowBack, ArrowUpward, ArrowDownward,
  Refresh, Download, Upload, Send, AttachFile, Link,
  Image, Videocam, MusicNote, PlayArrow, Pause, Stop,
  VolumeUp, Fullscreen, ZoomIn,
  ZoomOut, Filter, Sort, CalendarToday, Schedule, Person,
  People, Group, Lock, LockOpen, VpnKey, Shield, Gavel,
  Build, Code, Storage, Cloud, Wifi, Bluetooth,
  LocationOn, Map, Directions, Flight, DirectionsCar,
  Restaurant, Hotel, LocalHospital, School, Store, Business,
  Work, TrendingUp, TrendingDown, AttachMoney, CreditCard,
  AccountBalance, Receipt, Assignment, Note, List,
  ViewModule, FormatPaint, Brush, ColorLens,
  FormatBold, FormatItalic, FormatUnderlined,
  FormatListBulleted, FormatListNumbered, FormatAlignLeft,
  FormatAlignCenter, FormatAlignRight, Code as CodeIcon,
  GitHub, Google, Facebook, Twitter, Instagram, LinkedIn,
  YouTube, Chat,
  Forum, Comment, Reply, Forward, Inbox, Drafts,
  Archive, Flag, Label, Tag, Star,
  ThumbUp, ThumbDown, Mood, SentimentSatisfied, SentimentDissatisfied,
  LocalOffer, CardGiftcard, Redeem, Loyalty, Inventory,
  ShoppingCart as CartIcon, Category, Tune, ManageAccounts,
  DashboardCustomize, Web, Devices, PhoneAndroid, TabletMac,
  Laptop, Watch, Headphones, CameraAlt,
  FitnessCenter, SportsEsports, Construction,
  FiberManualRecord, MoreVert, MoreHoriz, ExpandMore, ExpandLess,
  ChevronLeft, ChevronRight, FirstPage, LastPage, SkipNext,
  SkipPrevious, FastForward, FastRewind, Replay, Shuffle,
  Repeat, VolumeDown, Hearing,
  Speed, Timer, AccessTime,
  Update, TrendingFlat, ShowChart, MultilineChart,
  PieChart, DonutLarge, BubbleChart, ScatterPlot, Assessment,
  Timeline, StackedLineChart, BarChart as BarChartIcon,
} from '@mui/icons-material';

// --- Lucide React icons ---
import {
  Zap, Heart, Star as LucideStar, Search as LucideSearch, User,
  Mail as LucideMail, Phone as LucidePhone, MapPin, Globe,
  Camera, Music, Video, FileText, Folder, Trash2, Edit3,
  Plus, Minus, Check as LucideCheck, X, ChevronDown, ChevronUp,
  ArrowRight, ArrowLeft, RotateCcw, Download as LucideDownload,
  Upload as LucideUpload, Share2, Bookmark as LucideBookmark,
  Lock as LucideLock, Unlock, Key, Shield as LucideShield,
  Eye, EyeOff, Bell, MessageCircle, Send as LucideSend,
  Calendar, Clock, Image as LucideImage, Film, Mic, Volume2,
  Wifi as LucideWifi, Battery, Signal, Monitor, Smartphone,
  Tablet, Headphones as LucideHeadphones, Printer, Cpu,
  Database, Server, Code as LucideCode, Terminal, GitBranch,
  Layers as LucideLayers, Layout, Grid, Maximize, Minimize,
  Copy, Clipboard, Scissors, File, FilePlus, FileMinus,
  Archive as LucideArchive, Tag as LucideTag, ShoppingCart as LucideCart,
  CreditCard as LucideCreditCard, DollarSign, TrendingUp as LucideTrendingUp,
  BarChart3, PieChart as LucidePieChart, Activity, Target,
  Award, Trophy, Medal, Flame, Sun, Moon,
  Cloud as LucideCloud, CloudRain, Snowflake, Wind, Thermometer,
  Umbrella, Map as LucideMap, Navigation, Compass, Anchor,
  Truck, Ship, Plane, Bike, Dumbbell,
} from 'lucide-react';

// --- React Icons (Font Awesome 6 + others) ---
import {
  FaHome, FaUser, FaCog, FaSearch, FaHeart, FaStar, FaEnvelope,
  FaPhone, FaMapMarkerAlt, FaGlobe, FaCamera, FaMusic, FaVideo,
  FaFile, FaFolder, FaTrash, FaEdit, FaPlus, FaMinus, FaCheck,
  FaTimes, FaArrowRight, FaArrowLeft, FaArrowUp, FaArrowDown,
  FaSync, FaDownload, FaUpload, FaShare, FaBookmark, FaLock,
  FaUnlock, FaKey, FaShieldAlt, FaEye, FaEyeSlash, FaBell, FaComment,
  FaPaperPlane, FaCalendar, FaClock, FaImage, FaMicrophone,
  FaWifi, FaBatteryFull, FaSignal, FaDesktop, FaMobileAlt, FaTabletAlt,
  FaHeadphones, FaPrint, FaMicrochip, FaDatabase, FaServer, FaCode,
  FaTerminal, FaCodeBranch, FaLayerGroup, FaThLarge, FaExpand, FaCompress,
  FaCopy, FaClipboard, FaCut, FaArchive, FaTags, FaShoppingCart,
  FaCreditCard, FaDollarSign, FaChartLine, FaChartBar, FaChartPie,
  FaChartArea, FaBullseye, FaTrophy, FaMedal, FaFire, FaSun, FaMoon,
  FaCloud, FaCloudRain, FaSnowflake, FaWind, FaThermometerHalf,
  FaUmbrella, FaMap, FaLocationArrow, FaCompass, FaAnchor,
  FaTruck, FaShip, FaPlane, FaBicycle, FaDumbbell,
  FaBolt, FaPaw, FaUtensils, FaBed, FaHospital,
  FaGraduationCap, FaStore, FaBuilding, FaBriefcase, FaMoneyBillWave,
  FaReceipt, FaPercentage, FaGift, FaTag, FaTicketAlt,
  FaPalette, FaPaintBrush, FaMagic, FaPen, FaPencilAlt,
  FaFont, FaAlignLeft, FaAlignCenter, FaAlignRight, FaListUl,
  FaListOl, FaBold, FaItalic, FaUnderline, FaStrikethrough,
  FaFacebook, FaTwitter, FaInstagram, FaLinkedin, FaYoutube,
  FaGithub, FaGoogle, FaReddit, FaPinterest, FaTelegram,
  FaWhatsapp, FaDiscord, FaSlack, FaTwitch, FaMedium,
} from 'react-icons/fa';

export interface IconEntry {
  name: string;
  component: ElementType;
  category: string;
  keywords: string[];
  library: IconLibraryId;
}

export type IconLibraryId = 'mui' | 'lucide' | 'fontawesome';

export interface IconLibraryMeta {
  id: IconLibraryId;
  label: string;
  count: number;
  description: string;
}

export const ICON_LIBRARIES: IconLibraryMeta[] = [
  { id: 'mui', label: 'Material Design', count: 0, description: 'Google Material Icons' },
  { id: 'lucide', label: 'Lucide', count: 0, description: 'Feather-inspired, MIT' },
  { id: 'fontawesome', label: 'Font Awesome', count: 0, description: 'Most popular icon set' },
];

export const ICON_CATEGORIES = [
  'Navigation',
  'Actions',
  'Communication',
  'Commerce',
  'Media',
  'Social',
  'Shapes',
  'Files',
  'Device',
  'Maps',
] as const;

// ── MUI Icons ──
const MUI_ICONS: IconEntry[] = [
  { name: 'Dashboard', component: Dashboard, category: 'Navigation', keywords: ['home', 'main', 'overview'], library: 'mui' },
  { name: 'Menu', component: Menu, category: 'Navigation', keywords: ['hamburger', 'nav', 'drawer'], library: 'mui' },
  { name: 'Close', component: Close, category: 'Navigation', keywords: ['dismiss', 'remove', 'cancel'], library: 'mui' },
  { name: 'ChevronLeft', component: ChevronLeft, category: 'Navigation', keywords: ['back', 'arrow', 'previous'], library: 'mui' },
  { name: 'ChevronRight', component: ChevronRight, category: 'Navigation', keywords: ['forward', 'arrow', 'next'], library: 'mui' },
  { name: 'ExpandMore', component: ExpandMore, category: 'Navigation', keywords: ['dropdown', 'accordion', 'down'], library: 'mui' },
  { name: 'ExpandLess', component: ExpandLess, category: 'Navigation', keywords: ['collapse', 'up', 'accordion'], library: 'mui' },
  { name: 'MoreVert', component: MoreVert, category: 'Navigation', keywords: ['dots', 'options', 'vertical'], library: 'mui' },
  { name: 'MoreHoriz', component: MoreHoriz, category: 'Navigation', keywords: ['dots', 'options', 'horizontal'], library: 'mui' },
  { name: 'FirstPage', component: FirstPage, category: 'Navigation', keywords: ['start', 'beginning'], library: 'mui' },
  { name: 'LastPage', component: LastPage, category: 'Navigation', keywords: ['end', 'finish'], library: 'mui' },
  { name: 'ArrowForward', component: ArrowForward, category: 'Navigation', keywords: ['arrow', 'next', 'right'], library: 'mui' },
  { name: 'ArrowBack', component: ArrowBack, category: 'Navigation', keywords: ['arrow', 'back', 'left'], library: 'mui' },
  { name: 'ArrowUpward', component: ArrowUpward, category: 'Navigation', keywords: ['arrow', 'up'], library: 'mui' },
  { name: 'ArrowDownward', component: ArrowDownward, category: 'Navigation', keywords: ['arrow', 'down'], library: 'mui' },
  { name: 'Home', component: Home, category: 'Navigation', keywords: ['house', 'main'], library: 'mui' },
  { name: 'Search', component: Search, category: 'Navigation', keywords: ['find', 'lookup', 'magnify'], library: 'mui' },
  { name: 'Filter', component: Filter, category: 'Navigation', keywords: ['sort', 'refine'], library: 'mui' },
  { name: 'Sort', component: Sort, category: 'Navigation', keywords: ['order', 'arrange'], library: 'mui' },
  { name: 'Tune', component: Tune, category: 'Navigation', keywords: ['settings', 'adjust', 'sliders'], library: 'mui' },
  { name: 'Web', component: Web, category: 'Navigation', keywords: ['internet', 'website', 'globe'], library: 'mui' },
  { name: 'Devices', component: Devices, category: 'Navigation', keywords: ['screens', 'responsive'], library: 'mui' },
  { name: 'Add', component: Add, category: 'Actions', keywords: ['create', 'new', 'plus'], library: 'mui' },
  { name: 'Remove', component: Remove, category: 'Actions', keywords: ['minus', 'subtract'], library: 'mui' },
  { name: 'Check', component: Check, category: 'Actions', keywords: ['done', 'complete', 'confirm'], library: 'mui' },
  { name: 'Edit', component: Edit, category: 'Actions', keywords: ['pencil', 'modify', 'write'], library: 'mui' },
  { name: 'Delete', component: Delete, category: 'Actions', keywords: ['trash', 'remove', 'destroy'], library: 'mui' },
  { name: 'Refresh', component: Refresh, category: 'Actions', keywords: ['reload', 'sync', 'update'], library: 'mui' },
  { name: 'Download', component: Download, category: 'Actions', keywords: ['save', 'export'], library: 'mui' },
  { name: 'Upload', component: Upload, category: 'Actions', keywords: ['import', 'send up'], library: 'mui' },
  { name: 'Send', component: Send, category: 'Actions', keywords: ['submit', 'paper plane'], library: 'mui' },
  { name: 'Share', component: Share, category: 'Actions', keywords: ['forward', 'distribute'], library: 'mui' },
  { name: 'Favorite', component: Favorite, category: 'Actions', keywords: ['heart', 'love', 'like'], library: 'mui' },
  { name: 'Star', component: Star, category: 'Actions', keywords: ['rating', 'bookmark', 'important'], library: 'mui' },
  { name: 'ThumbUp', component: ThumbUp, category: 'Actions', keywords: ['like', 'approve'], library: 'mui' },
  { name: 'ThumbDown', component: ThumbDown, category: 'Actions', keywords: ['dislike', 'reject'], library: 'mui' },
  { name: 'Bookmark', component: Bookmark, category: 'Actions', keywords: ['save', 'flag'], library: 'mui' },
  { name: 'Flag', component: Flag, category: 'Actions', keywords: ['report', 'important'], library: 'mui' },
  { name: 'AttachFile', component: AttachFile, category: 'Actions', keywords: ['clip', 'paperclip'], library: 'mui' },
  { name: 'Link', component: Link, category: 'Actions', keywords: ['chain', 'url', 'hyperlink'], library: 'mui' },
  { name: 'Build', component: Build, category: 'Actions', keywords: ['tools', 'wrench', 'settings'], library: 'mui' },
  { name: 'Code', component: CodeIcon, category: 'Actions', keywords: ['developer', 'programming'], library: 'mui' },
  { name: 'Lock', component: Lock, category: 'Actions', keywords: ['security', 'private', 'password'], library: 'mui' },
  { name: 'LockOpen', component: LockOpen, category: 'Actions', keywords: ['unlock', 'public'], library: 'mui' },
  { name: 'VpnKey', component: VpnKey, category: 'Actions', keywords: ['key', 'access'], library: 'mui' },
  { name: 'Shield', component: Shield, category: 'Actions', keywords: ['security', 'protect'], library: 'mui' },
  { name: 'Settings', component: Settings, category: 'Actions', keywords: ['gear', 'cog', 'config'], library: 'mui' },
  { name: 'Mail', component: Mail, category: 'Communication', keywords: ['email', 'envelope', 'message'], library: 'mui' },
  { name: 'Chat', component: Chat, category: 'Communication', keywords: ['message', 'bubble', 'conversation'], library: 'mui' },
  { name: 'Phone', component: Phone, category: 'Communication', keywords: ['call', 'telephone'], library: 'mui' },
  { name: 'Forum', component: Forum, category: 'Communication', keywords: ['discussion', 'community'], library: 'mui' },
  { name: 'Comment', component: Comment, category: 'Communication', keywords: ['note', 'remark'], library: 'mui' },
  { name: 'Notifications', component: Notifications, category: 'Communication', keywords: ['bell', 'alert', 'alarm'], library: 'mui' },
  { name: 'Inbox', component: Inbox, category: 'Communication', keywords: ['mail', 'messages'], library: 'mui' },
  { name: 'Drafts', component: Drafts, category: 'Communication', keywords: ['email', 'unsent'], library: 'mui' },
  { name: 'Reply', component: Reply, category: 'Communication', keywords: ['respond', 'back'], library: 'mui' },
  { name: 'Forward', component: Forward, category: 'Communication', keywords: ['send', 'ahead'], library: 'mui' },
  { name: 'Label', component: Label, category: 'Communication', keywords: ['tag', 'badge'], library: 'mui' },
  { name: 'Tag', component: Tag, category: 'Communication', keywords: ['label', 'category'], library: 'mui' },
  { name: 'LocalOffer', component: LocalOffer, category: 'Communication', keywords: ['price', 'deal', 'sale'], library: 'mui' },
  { name: 'ShoppingCart', component: CartIcon, category: 'Commerce', keywords: ['cart', 'buy', 'purchase'], library: 'mui' },
  { name: 'Store', component: Store, category: 'Commerce', keywords: ['shop', 'retail'], library: 'mui' },
  { name: 'AttachMoney', component: AttachMoney, category: 'Commerce', keywords: ['dollar', 'price', 'cost'], library: 'mui' },
  { name: 'CreditCard', component: CreditCard, category: 'Commerce', keywords: ['payment', 'card', 'pay'], library: 'mui' },
  { name: 'AccountBalance', component: AccountBalance, category: 'Commerce', keywords: ['bank', 'finance'], library: 'mui' },
  { name: 'Receipt', component: Receipt, category: 'Commerce', keywords: ['bill', 'invoice'], library: 'mui' },
  { name: 'TrendingUp', component: TrendingUp, category: 'Commerce', keywords: ['growth', 'increase', 'up'], library: 'mui' },
  { name: 'TrendingDown', component: TrendingDown, category: 'Commerce', keywords: ['decline', 'decrease', 'down'], library: 'mui' },
  { name: 'Work', component: Work, category: 'Commerce', keywords: ['briefcase', 'job', 'career'], library: 'mui' },
  { name: 'Business', component: Business, category: 'Commerce', keywords: ['office', 'building', 'company'], library: 'mui' },
  { name: 'Category', component: Category, category: 'Commerce', keywords: ['group', 'type', 'classification'], library: 'mui' },
  { name: 'Inventory', component: Inventory, category: 'Commerce', keywords: ['stock', 'warehouse', 'product'], library: 'mui' },
  { name: 'Redeem', component: Redeem, category: 'Commerce', keywords: ['gift', 'voucher', 'coupon'], library: 'mui' },
  { name: 'CardGiftcard', component: CardGiftcard, category: 'Commerce', keywords: ['gift', 'present'], library: 'mui' },
  { name: 'Loyalty', component: Loyalty, category: 'Commerce', keywords: ['points', 'rewards'], library: 'mui' },
  { name: 'Assessment', component: Assessment, category: 'Commerce', keywords: ['chart', 'analytics', 'report'], library: 'mui' },
  { name: 'PieChart', component: PieChart, category: 'Commerce', keywords: ['graph', 'donut', 'data'], library: 'mui' },
  { name: 'BarChart', component: BarChartIcon, category: 'Commerce', keywords: ['graph', 'analytics', 'data'], library: 'mui' },
  { name: 'ShowChart', component: ShowChart, category: 'Commerce', keywords: ['line', 'graph', 'trend'], library: 'mui' },
  { name: 'Timeline', component: Timeline, category: 'Commerce', keywords: ['history', 'progress'], library: 'mui' },
  { name: 'Image', component: Image, category: 'Media', keywords: ['photo', 'picture', 'gallery'], library: 'mui' },
  { name: 'Brush', component: Brush, category: 'Media', keywords: ['paint', 'draw', 'art'], library: 'mui' },
  { name: 'Palette', component: Palette, category: 'Media', keywords: ['color', 'paint'], library: 'mui' },
  { name: 'ColorLens', component: ColorLens, category: 'Media', keywords: ['color', 'dropper'], library: 'mui' },
  { name: 'FormatPaint', component: FormatPaint, category: 'Media', keywords: ['paint', 'bucket', 'fill'], library: 'mui' },
  { name: 'CameraAlt', component: CameraAlt, category: 'Media', keywords: ['photo', 'camera', 'picture'], library: 'mui' },
  { name: 'PlayArrow', component: PlayArrow, category: 'Media', keywords: ['video', 'start', 'begin'], library: 'mui' },
  { name: 'Pause', component: Pause, category: 'Media', keywords: ['video', 'stop', 'hold'], library: 'mui' },
  { name: 'Stop', component: Stop, category: 'Media', keywords: ['video', 'end', 'halt'], library: 'mui' },
  { name: 'VolumeUp', component: VolumeUp, category: 'Media', keywords: ['sound', 'audio', 'loud'], library: 'mui' },
  { name: 'MusicNote', component: MusicNote, category: 'Media', keywords: ['audio', 'song'], library: 'mui' },
  { name: 'Speed', component: Speed, category: 'Media', keywords: ['fast', 'velocity', 'gauge'], library: 'mui' },
  { name: 'Person', component: Person, category: 'Social', keywords: ['user', 'avatar', 'profile'], library: 'mui' },
  { name: 'People', component: People, category: 'Social', keywords: ['users', 'group', 'team'], library: 'mui' },
  { name: 'Group', component: Group, category: 'Social', keywords: ['users', 'community'], library: 'mui' },
  { name: 'AccountCircle', component: AccountCircle, category: 'Social', keywords: ['avatar', 'profile', 'circle'], library: 'mui' },
  { name: 'Mood', component: Mood, category: 'Social', keywords: ['emoji', 'face', 'happy'], library: 'mui' },
  { name: 'SentimentSatisfied', component: SentimentSatisfied, category: 'Social', keywords: ['smile', 'face'], library: 'mui' },
  { name: 'SentimentDissatisfied', component: SentimentDissatisfied, category: 'Social', keywords: ['sad', 'face'], library: 'mui' },
  { name: 'School', component: School, category: 'Social', keywords: ['education', 'university'], library: 'mui' },
  { name: 'Restaurant', component: Restaurant, category: 'Social', keywords: ['food', 'dining'], library: 'mui' },
  { name: 'FitnessCenter', component: FitnessCenter, category: 'Social', keywords: ['gym', 'exercise'], library: 'mui' },
  { name: 'LocalHospital', component: LocalHospital, category: 'Social', keywords: ['medical', 'health'], library: 'mui' },
  { name: 'SportsEsports', component: SportsEsports, category: 'Social', keywords: ['gaming', 'game'], library: 'mui' },
  { name: 'CheckCircle', component: CheckCircle, category: 'Shapes', keywords: ['success', 'done', 'circle'], library: 'mui' },
  { name: 'Warning', component: Warning, category: 'Shapes', keywords: ['alert', 'caution', 'triangle'], library: 'mui' },
  { name: 'Info', component: Info, category: 'Shapes', keywords: ['information', 'circle', 'help'], library: 'mui' },
  { name: 'Error', component: Error, category: 'Shapes', keywords: ['alert', 'danger', 'circle'], library: 'mui' },
  { name: 'CropSquare', component: CropSquare, category: 'Shapes', keywords: ['square', 'box', 'frame'], library: 'mui' },
  { name: 'FiberManualRecord', component: FiberManualRecord, category: 'Shapes', keywords: ['circle', 'dot', 'point'], library: 'mui' },
  { name: 'BubbleChart', component: BubbleChart, category: 'Shapes', keywords: ['circles', 'abstract'], library: 'mui' },
  { name: 'Assignment', component: Assignment, category: 'Files', keywords: ['task', 'document'], library: 'mui' },
  { name: 'Note', component: Note, category: 'Files', keywords: ['memo', 'text'], library: 'mui' },
  { name: 'List', component: List, category: 'Files', keywords: ['items', 'rows'], library: 'mui' },
  { name: 'Archive', component: Archive, category: 'Files', keywords: ['storage', 'box'], library: 'mui' },
  { name: 'PhoneAndroid', component: PhoneAndroid, category: 'Device', keywords: ['mobile', 'smartphone'], library: 'mui' },
  { name: 'TabletMac', component: TabletMac, category: 'Device', keywords: ['tablet', 'ipad'], library: 'mui' },
  { name: 'Laptop', component: Laptop, category: 'Device', keywords: ['computer', 'notebook'], library: 'mui' },
  { name: 'DesktopWindows', component: DesktopWindows, category: 'Device', keywords: ['monitor', 'pc'], library: 'mui' },
  { name: 'Watch', component: Watch, category: 'Device', keywords: ['wearable', 'smartwatch'], library: 'mui' },
  { name: 'Headphones', component: Headphones, category: 'Device', keywords: ['audio', 'earphones'], library: 'mui' },
  { name: 'Wifi', component: Wifi, category: 'Device', keywords: ['internet', 'wireless', 'signal'], library: 'mui' },
  { name: 'Bluetooth', component: Bluetooth, category: 'Device', keywords: ['wireless', 'connect'], library: 'mui' },
  { name: 'Cloud', component: Cloud, category: 'Device', keywords: ['storage', 'server', 'online'], library: 'mui' },
  { name: 'Storage', component: Storage, category: 'Device', keywords: ['database', 'server'], library: 'mui' },
  { name: 'LocationOn', component: LocationOn, category: 'Maps', keywords: ['pin', 'marker', 'map'], library: 'mui' },
  { name: 'Map', component: Map, category: 'Maps', keywords: ['location', 'navigation'], library: 'mui' },
  { name: 'Directions', component: Directions, category: 'Maps', keywords: ['route', 'navigate'], library: 'mui' },
  { name: 'Flight', component: Flight, category: 'Maps', keywords: ['airplane', 'travel'], library: 'mui' },
  { name: 'DirectionsCar', component: DirectionsCar, category: 'Maps', keywords: ['car', 'drive', 'vehicle'], library: 'mui' },
  { name: 'CalendarToday', component: CalendarToday, category: 'Navigation', keywords: ['date', 'calendar'], library: 'mui' },
  { name: 'Schedule', component: Schedule, category: 'Navigation', keywords: ['time', 'clock'], library: 'mui' },
  { name: 'AccessTime', component: AccessTime, category: 'Navigation', keywords: ['clock', 'time'], library: 'mui' },
  { name: 'Timer', component: Timer, category: 'Navigation', keywords: ['stopwatch', 'countdown'], library: 'mui' },
  { name: 'ManageAccounts', component: ManageAccounts, category: 'Actions', keywords: ['user', 'settings'], library: 'mui' },
  { name: 'Gavel', component: Gavel, category: 'Actions', keywords: ['law', 'legal', 'judge'], library: 'mui' },
  { name: 'Construction', component: Construction, category: 'Actions', keywords: ['tools', 'work'], library: 'mui' },
  { name: 'Widgets', component: Widgets, category: 'Navigation', keywords: ['components', 'blocks'], library: 'mui' },
  { name: 'Layers', component: Layers, category: 'Navigation', keywords: ['stack', 'depth'], library: 'mui' },
  { name: 'Animation', component: Animation, category: 'Navigation', keywords: ['motion', 'animate'], library: 'mui' },
  { name: 'Gradient', component: Gradient, category: 'Navigation', keywords: ['color', 'transition'], library: 'mui' },
  { name: 'TextFields', component: TextFields, category: 'Navigation', keywords: ['text', 'type', 'input'], library: 'mui' },
  { name: 'SpaceBar', component: SpaceBar, category: 'Navigation', keywords: ['spacing', 'gap'], library: 'mui' },
  { name: 'Visibility', component: Visibility, category: 'Navigation', keywords: ['eye', 'show', 'view'], library: 'mui' },
  { name: 'DashboardCustomize', component: DashboardCustomize, category: 'Navigation', keywords: ['layout', 'customize'], library: 'mui' },
  { name: 'FormatBold', component: FormatBold, category: 'Media', keywords: ['text', 'bold', 'strong'], library: 'mui' },
  { name: 'FormatItalic', component: FormatItalic, category: 'Media', keywords: ['text', 'italic', 'emphasis'], library: 'mui' },
  { name: 'FormatUnderlined', component: FormatUnderlined, category: 'Media', keywords: ['text', 'underline'], library: 'mui' },
  { name: 'FormatListBulleted', component: FormatListBulleted, category: 'Media', keywords: ['list', 'bullets'], library: 'mui' },
  { name: 'FormatListNumbered', component: FormatListNumbered, category: 'Media', keywords: ['list', 'numbers'], library: 'mui' },
  { name: 'FormatAlignLeft', component: FormatAlignLeft, category: 'Media', keywords: ['align', 'left'], library: 'mui' },
  { name: 'FormatAlignCenter', component: FormatAlignCenter, category: 'Media', keywords: ['align', 'center'], library: 'mui' },
  { name: 'FormatAlignRight', component: FormatAlignRight, category: 'Media', keywords: ['align', 'right'], library: 'mui' },
  { name: 'TrendingFlat', component: TrendingFlat, category: 'Commerce', keywords: ['neutral', 'steady'], library: 'mui' },
  { name: 'MultilineChart', component: MultilineChart, category: 'Commerce', keywords: ['graph', 'lines', 'data'], library: 'mui' },
  { name: 'StackedLineChart', component: StackedLineChart, category: 'Commerce', keywords: ['graph', 'area'], library: 'mui' },
  { name: 'DonutLarge', component: DonutLarge, category: 'Commerce', keywords: ['donut', 'chart', 'ring'], library: 'mui' },
  { name: 'ScatterPlot', component: ScatterPlot, category: 'Commerce', keywords: ['graph', 'dots', 'data'], library: 'mui' },
];

// ── Lucide Icons ──
const LUCIDE_ICONS: IconEntry[] = [
  { name: 'Zap', component: Zap, category: 'Actions', keywords: ['bolt', 'lightning', 'fast'], library: 'lucide' },
  { name: 'Heart', component: Heart, category: 'Actions', keywords: ['love', 'like', 'favorite'], library: 'lucide' },
  { name: 'Star', component: LucideStar, category: 'Actions', keywords: ['rating', 'bookmark', 'favorite'], library: 'lucide' },
  { name: 'Search', component: LucideSearch, category: 'Navigation', keywords: ['find', 'lookup', 'magnify'], library: 'lucide' },
  { name: 'User', component: User, category: 'Social', keywords: ['person', 'profile', 'avatar'], library: 'lucide' },
  { name: 'Mail', component: LucideMail, category: 'Communication', keywords: ['email', 'envelope', 'message'], library: 'lucide' },
  { name: 'Phone', component: LucidePhone, category: 'Communication', keywords: ['call', 'telephone'], library: 'lucide' },
  { name: 'MapPin', component: MapPin, category: 'Maps', keywords: ['location', 'pin', 'marker'], library: 'lucide' },
  { name: 'Globe', component: Globe, category: 'Navigation', keywords: ['world', 'earth', 'web'], library: 'lucide' },
  { name: 'Camera', component: Camera, category: 'Media', keywords: ['photo', 'picture'], library: 'lucide' },
  { name: 'Music', component: Music, category: 'Media', keywords: ['audio', 'song'], library: 'lucide' },
  { name: 'Video', component: Video, category: 'Media', keywords: ['film', 'movie'], library: 'lucide' },
  { name: 'FileText', component: FileText, category: 'Files', keywords: ['document', 'page'], library: 'lucide' },
  { name: 'Folder', component: Folder, category: 'Files', keywords: ['directory', 'storage'], library: 'lucide' },
  { name: 'Trash', component: Trash2, category: 'Actions', keywords: ['delete', 'remove', 'bin'], library: 'lucide' },
  { name: 'Edit', component: Edit3, category: 'Actions', keywords: ['pencil', 'write', 'modify'], library: 'lucide' },
  { name: 'Plus', component: Plus, category: 'Actions', keywords: ['add', 'create', 'new'], library: 'lucide' },
  { name: 'Minus', component: Minus, category: 'Actions', keywords: ['remove', 'subtract'], library: 'lucide' },
  { name: 'Check', component: LucideCheck, category: 'Actions', keywords: ['done', 'complete', 'success'], library: 'lucide' },
  { name: 'X', component: X, category: 'Actions', keywords: ['close', 'cancel', 'remove'], library: 'lucide' },
  { name: 'ChevronDown', component: ChevronDown, category: 'Navigation', keywords: ['arrow', 'dropdown'], library: 'lucide' },
  { name: 'ChevronUp', component: ChevronUp, category: 'Navigation', keywords: ['arrow', 'collapse'], library: 'lucide' },
  { name: 'ArrowRight', component: ArrowRight, category: 'Navigation', keywords: ['arrow', 'next', 'forward'], library: 'lucide' },
  { name: 'ArrowLeft', component: ArrowLeft, category: 'Navigation', keywords: ['arrow', 'back', 'previous'], library: 'lucide' },
  { name: 'RotateCcw', component: RotateCcw, category: 'Actions', keywords: ['reload', 'refresh', 'undo'], library: 'lucide' },
  { name: 'Download', component: LucideDownload, category: 'Actions', keywords: ['save', 'export'], library: 'lucide' },
  { name: 'Upload', component: LucideUpload, category: 'Actions', keywords: ['import', 'send'], library: 'lucide' },
  { name: 'Share', component: Share2, category: 'Actions', keywords: ['forward', 'distribute'], library: 'lucide' },
  { name: 'Bookmark', component: LucideBookmark, category: 'Actions', keywords: ['save', 'flag'], library: 'lucide' },
  { name: 'Lock', component: LucideLock, category: 'Actions', keywords: ['security', 'private'], library: 'lucide' },
  { name: 'Unlock', component: Unlock, category: 'Actions', keywords: ['open', 'public'], library: 'lucide' },
  { name: 'Key', component: Key, category: 'Actions', keywords: ['access', 'password'], library: 'lucide' },
  { name: 'Shield', component: LucideShield, category: 'Actions', keywords: ['security', 'protect'], library: 'lucide' },
  { name: 'Eye', component: Eye, category: 'Actions', keywords: ['view', 'show', 'visible'], library: 'lucide' },
  { name: 'EyeOff', component: EyeOff, category: 'Actions', keywords: ['hide', 'invisible'], library: 'lucide' },
  { name: 'Bell', component: Bell, category: 'Communication', keywords: ['notification', 'alert', 'alarm'], library: 'lucide' },
  { name: 'MessageCircle', component: MessageCircle, category: 'Communication', keywords: ['chat', 'comment', 'bubble'], library: 'lucide' },
  { name: 'Send', component: LucideSend, category: 'Communication', keywords: ['submit', 'paper plane'], library: 'lucide' },
  { name: 'Calendar', component: Calendar, category: 'Navigation', keywords: ['date', 'schedule'], library: 'lucide' },
  { name: 'Clock', component: Clock, category: 'Navigation', keywords: ['time', 'watch'], library: 'lucide' },
  { name: 'Image', component: LucideImage, category: 'Media', keywords: ['photo', 'picture'], library: 'lucide' },
  { name: 'Film', component: Film, category: 'Media', keywords: ['movie', 'video'], library: 'lucide' },
  { name: 'Mic', component: Mic, category: 'Media', keywords: ['microphone', 'record', 'audio'], library: 'lucide' },
  { name: 'Volume', component: Volume2, category: 'Media', keywords: ['sound', 'audio'], library: 'lucide' },
  { name: 'Wifi', component: LucideWifi, category: 'Device', keywords: ['internet', 'wireless', 'signal'], library: 'lucide' },
  { name: 'Battery', component: Battery, category: 'Device', keywords: ['power', 'charge'], library: 'lucide' },
  { name: 'Signal', component: Signal, category: 'Device', keywords: ['connection', 'strength'], library: 'lucide' },
  { name: 'Monitor', component: Monitor, category: 'Device', keywords: ['desktop', 'screen', 'display'], library: 'lucide' },
  { name: 'Smartphone', component: Smartphone, category: 'Device', keywords: ['mobile', 'phone'], library: 'lucide' },
  { name: 'Tablet', component: Tablet, category: 'Device', keywords: ['ipad', 'device'], library: 'lucide' },
  { name: 'Headphones', component: LucideHeadphones, category: 'Device', keywords: ['audio', 'earphones'], library: 'lucide' },
  { name: 'Printer', component: Printer, category: 'Device', keywords: ['print', 'paper'], library: 'lucide' },
  { name: 'Cpu', component: Cpu, category: 'Device', keywords: ['processor', 'chip'], library: 'lucide' },
  { name: 'Database', component: Database, category: 'Device', keywords: ['storage', 'server'], library: 'lucide' },
  { name: 'Server', component: Server, category: 'Device', keywords: ['hosting', 'backend'], library: 'lucide' },
  { name: 'Code', component: LucideCode, category: 'Actions', keywords: ['programming', 'developer'], library: 'lucide' },
  { name: 'Terminal', component: Terminal, category: 'Actions', keywords: ['console', 'command'], library: 'lucide' },
  { name: 'GitBranch', component: GitBranch, category: 'Actions', keywords: ['version', 'branch', 'git'], library: 'lucide' },
  { name: 'Layers', component: LucideLayers, category: 'Navigation', keywords: ['stack', 'depth'], library: 'lucide' },
  { name: 'Layout', component: Layout, category: 'Navigation', keywords: ['template', 'grid'], library: 'lucide' },
  { name: 'Grid', component: Grid, category: 'Navigation', keywords: ['layout', 'tiles'], library: 'lucide' },
  { name: 'Maximize', component: Maximize, category: 'Actions', keywords: ['fullscreen', 'expand'], library: 'lucide' },
  { name: 'Minimize', component: Minimize, category: 'Actions', keywords: ['shrink', 'compress'], library: 'lucide' },
  { name: 'Copy', component: Copy, category: 'Actions', keywords: ['duplicate', 'paste'], library: 'lucide' },
  { name: 'Clipboard', component: Clipboard, category: 'Files', keywords: ['paste', 'copy'], library: 'lucide' },
  { name: 'Scissors', component: Scissors, category: 'Actions', keywords: ['cut', 'trim'], library: 'lucide' },
  { name: 'File', component: File, category: 'Files', keywords: ['document', 'page'], library: 'lucide' },
  { name: 'Archive', component: LucideArchive, category: 'Files', keywords: ['storage', 'box'], library: 'lucide' },
  { name: 'Tag', component: LucideTag, category: 'Commerce', keywords: ['label', 'price'], library: 'lucide' },
  { name: 'ShoppingCart', component: LucideCart, category: 'Commerce', keywords: ['cart', 'buy'], library: 'lucide' },
  { name: 'CreditCard', component: LucideCreditCard, category: 'Commerce', keywords: ['payment', 'card'], library: 'lucide' },
  { name: 'DollarSign', component: DollarSign, category: 'Commerce', keywords: ['money', 'price', 'cost'], library: 'lucide' },
  { name: 'TrendingUp', component: LucideTrendingUp, category: 'Commerce', keywords: ['growth', 'increase'], library: 'lucide' },
  { name: 'BarChart', component: BarChart3, category: 'Commerce', keywords: ['graph', 'analytics'], library: 'lucide' },
  { name: 'PieChart', component: LucidePieChart, category: 'Commerce', keywords: ['graph', 'donut'], library: 'lucide' },
  { name: 'Activity', component: Activity, category: 'Commerce', keywords: ['heartbeat', 'monitor'], library: 'lucide' },
  { name: 'Target', component: Target, category: 'Commerce', keywords: ['goal', 'aim', 'bullseye'], library: 'lucide' },
  { name: 'Award', component: Award, category: 'Social', keywords: ['prize', 'medal', 'achievement'], library: 'lucide' },
  { name: 'Trophy', component: Trophy, category: 'Social', keywords: ['winner', 'champion'], library: 'lucide' },
  { name: 'Flame', component: Flame, category: 'Social', keywords: ['fire', 'trending', 'hot'], library: 'lucide' },
  { name: 'Sun', component: Sun, category: 'Shapes', keywords: ['light', 'day', 'bright'], library: 'lucide' },
  { name: 'Moon', component: Moon, category: 'Shapes', keywords: ['dark', 'night', 'theme'], library: 'lucide' },
  { name: 'Cloud', component: LucideCloud, category: 'Device', keywords: ['storage', 'server', 'online'], library: 'lucide' },
  { name: 'CloudRain', component: CloudRain, category: 'Device', keywords: ['weather', 'rain'], library: 'lucide' },
  { name: 'Snowflake', component: Snowflake, category: 'Shapes', keywords: ['winter', 'cold', 'ice'], library: 'lucide' },
  { name: 'Wind', component: Wind, category: 'Device', keywords: ['air', 'breeze', 'weather'], library: 'lucide' },
  { name: 'Map', component: LucideMap, category: 'Maps', keywords: ['location', 'navigation'], library: 'lucide' },
  { name: 'Navigation', component: Navigation, category: 'Maps', keywords: ['compass', 'direction'], library: 'lucide' },
  { name: 'Compass', component: Compass, category: 'Maps', keywords: ['direction', 'navigation'], library: 'lucide' },
  { name: 'Anchor', component: Anchor, category: 'Maps', keywords: ['ship', 'port', 'marine'], library: 'lucide' },
  { name: 'Truck', component: Truck, category: 'Commerce', keywords: ['delivery', 'transport'], library: 'lucide' },
  { name: 'Plane', component: Plane, category: 'Maps', keywords: ['airplane', 'travel', 'flight'], library: 'lucide' },
  { name: 'Bike', component: Bike, category: 'Maps', keywords: ['bicycle', 'cycle'], library: 'lucide' },
  { name: 'Dumbbell', component: Dumbbell, category: 'Social', keywords: ['gym', 'fitness', 'exercise'], library: 'lucide' },
];

// ── Font Awesome Icons (via react-icons) ──
const FA_ICONS: IconEntry[] = [
  { name: 'FaHome', component: FaHome, category: 'Navigation', keywords: ['house', 'main'], library: 'fontawesome' },
  { name: 'FaUser', component: FaUser, category: 'Social', keywords: ['person', 'profile'], library: 'fontawesome' },
  { name: 'FaCog', component: FaCog, category: 'Actions', keywords: ['settings', 'gear', 'config'], library: 'fontawesome' },
  { name: 'FaSearch', component: FaSearch, category: 'Navigation', keywords: ['find', 'lookup'], library: 'fontawesome' },
  { name: 'FaHeart', component: FaHeart, category: 'Actions', keywords: ['love', 'like'], library: 'fontawesome' },
  { name: 'FaStar', component: FaStar, category: 'Actions', keywords: ['rating', 'favorite'], library: 'fontawesome' },
  { name: 'FaEnvelope', component: FaEnvelope, category: 'Communication', keywords: ['email', 'mail'], library: 'fontawesome' },
  { name: 'FaPhone', component: FaPhone, category: 'Communication', keywords: ['call', 'telephone'], library: 'fontawesome' },
  { name: 'FaMapMarkerAlt', component: FaMapMarkerAlt, category: 'Maps', keywords: ['location', 'pin'], library: 'fontawesome' },
  { name: 'FaGlobe', component: FaGlobe, category: 'Navigation', keywords: ['world', 'web', 'earth'], library: 'fontawesome' },
  { name: 'FaCamera', component: FaCamera, category: 'Media', keywords: ['photo', 'picture'], library: 'fontawesome' },
  { name: 'FaMusic', component: FaMusic, category: 'Media', keywords: ['audio', 'song'], library: 'fontawesome' },
  { name: 'FaVideo', component: FaVideo, category: 'Media', keywords: ['film', 'movie'], library: 'fontawesome' },
  { name: 'FaFile', component: FaFile, category: 'Files', keywords: ['document', 'page'], library: 'fontawesome' },
  { name: 'FaFolder', component: FaFolder, category: 'Files', keywords: ['directory', 'storage'], library: 'fontawesome' },
  { name: 'FaTrash', component: FaTrash, category: 'Actions', keywords: ['delete', 'remove'], library: 'fontawesome' },
  { name: 'FaEdit', component: FaEdit, category: 'Actions', keywords: ['pencil', 'write'], library: 'fontawesome' },
  { name: 'FaPlus', component: FaPlus, category: 'Actions', keywords: ['add', 'create'], library: 'fontawesome' },
  { name: 'FaMinus', component: FaMinus, category: 'Actions', keywords: ['remove', 'subtract'], library: 'fontawesome' },
  { name: 'FaCheck', component: FaCheck, category: 'Actions', keywords: ['done', 'complete'], library: 'fontawesome' },
  { name: 'FaTimes', component: FaTimes, category: 'Actions', keywords: ['close', 'cancel'], library: 'fontawesome' },
  { name: 'FaArrowRight', component: FaArrowRight, category: 'Navigation', keywords: ['next', 'forward'], library: 'fontawesome' },
  { name: 'FaArrowLeft', component: FaArrowLeft, category: 'Navigation', keywords: ['back', 'previous'], library: 'fontawesome' },
  { name: 'FaArrowUp', component: FaArrowUp, category: 'Navigation', keywords: ['up', 'top'], library: 'fontawesome' },
  { name: 'FaArrowDown', component: FaArrowDown, category: 'Navigation', keywords: ['down', 'bottom'], library: 'fontawesome' },
  { name: 'FaSync', component: FaSync, category: 'Actions', keywords: ['reload', 'refresh'], library: 'fontawesome' },
  { name: 'FaDownload', component: FaDownload, category: 'Actions', keywords: ['save', 'export'], library: 'fontawesome' },
  { name: 'FaUpload', component: FaUpload, category: 'Actions', keywords: ['import', 'send'], library: 'fontawesome' },
  { name: 'FaShare', component: FaShare, category: 'Actions', keywords: ['forward', 'distribute'], library: 'fontawesome' },
  { name: 'FaBookmark', component: FaBookmark, category: 'Actions', keywords: ['save', 'flag'], library: 'fontawesome' },
  { name: 'FaLock', component: FaLock, category: 'Actions', keywords: ['security', 'private'], library: 'fontawesome' },
  { name: 'FaUnlock', component: FaUnlock, category: 'Actions', keywords: ['open', 'public'], library: 'fontawesome' },
  { name: 'FaKey', component: FaKey, category: 'Actions', keywords: ['access', 'password'], library: 'fontawesome' },
  { name: 'FaShieldAlt', component: FaShieldAlt, category: 'Actions', keywords: ['security', 'protect'], library: 'fontawesome' },
  { name: 'FaEye', component: FaEye, category: 'Actions', keywords: ['view', 'show'], library: 'fontawesome' },
  { name: 'FaEyeSlash', component: FaEyeSlash, category: 'Actions', keywords: ['hide', 'invisible'], library: 'fontawesome' },
  { name: 'FaBell', component: FaBell, category: 'Communication', keywords: ['notification', 'alert'], library: 'fontawesome' },
  { name: 'FaComment', component: FaComment, category: 'Communication', keywords: ['chat', 'bubble'], library: 'fontawesome' },
  { name: 'FaPaperPlane', component: FaPaperPlane, category: 'Communication', keywords: ['send', 'submit'], library: 'fontawesome' },
  { name: 'FaCalendar', component: FaCalendar, category: 'Navigation', keywords: ['date', 'schedule'], library: 'fontawesome' },
  { name: 'FaClock', component: FaClock, category: 'Navigation', keywords: ['time', 'watch'], library: 'fontawesome' },
  { name: 'FaImage', component: FaImage, category: 'Media', keywords: ['photo', 'picture'], library: 'fontawesome' },
  { name: 'FaMicrophone', component: FaMicrophone, category: 'Media', keywords: ['record', 'audio'], library: 'fontawesome' },
  { name: 'FaWifi', component: FaWifi, category: 'Device', keywords: ['internet', 'wireless'], library: 'fontawesome' },
  { name: 'FaBatteryFull', component: FaBatteryFull, category: 'Device', keywords: ['power', 'charge'], library: 'fontawesome' },
  { name: 'FaSignal', component: FaSignal, category: 'Device', keywords: ['connection', 'strength'], library: 'fontawesome' },
  { name: 'FaDesktop', component: FaDesktop, category: 'Device', keywords: ['monitor', 'screen'], library: 'fontawesome' },
  { name: 'FaMobileAlt', component: FaMobileAlt, category: 'Device', keywords: ['phone', 'smartphone'], library: 'fontawesome' },
  { name: 'FaTabletAlt', component: FaTabletAlt, category: 'Device', keywords: ['ipad', 'device'], library: 'fontawesome' },
  { name: 'FaHeadphones', component: FaHeadphones, category: 'Device', keywords: ['audio', 'earphones'], library: 'fontawesome' },
  { name: 'FaPrint', component: FaPrint, category: 'Device', keywords: ['printer', 'paper'], library: 'fontawesome' },
  { name: 'FaMicrochip', component: FaMicrochip, category: 'Device', keywords: ['processor', 'chip'], library: 'fontawesome' },
  { name: 'FaDatabase', component: FaDatabase, category: 'Device', keywords: ['storage', 'server'], library: 'fontawesome' },
  { name: 'FaServer', component: FaServer, category: 'Device', keywords: ['hosting', 'backend'], library: 'fontawesome' },
  { name: 'FaCode', component: FaCode, category: 'Actions', keywords: ['programming', 'developer'], library: 'fontawesome' },
  { name: 'FaTerminal', component: FaTerminal, category: 'Actions', keywords: ['console', 'command'], library: 'fontawesome' },
  { name: 'FaCodeBranch', component: FaCodeBranch, category: 'Actions', keywords: ['version', 'branch'], library: 'fontawesome' },
  { name: 'FaLayerGroup', component: FaLayerGroup, category: 'Navigation', keywords: ['stack', 'layers'], library: 'fontawesome' },
  { name: 'FaThLarge', component: FaThLarge, category: 'Navigation', keywords: ['grid', 'layout'], library: 'fontawesome' },
  { name: 'FaExpand', component: FaExpand, category: 'Actions', keywords: ['fullscreen', 'maximize'], library: 'fontawesome' },
  { name: 'FaCompress', component: FaCompress, category: 'Actions', keywords: ['shrink', 'minimize'], library: 'fontawesome' },
  { name: 'FaCopy', component: FaCopy, category: 'Actions', keywords: ['duplicate', 'paste'], library: 'fontawesome' },
  { name: 'FaClipboard', component: FaClipboard, category: 'Files', keywords: ['paste', 'copy'], library: 'fontawesome' },
  { name: 'FaCut', component: FaCut, category: 'Actions', keywords: ['scissors', 'trim'], library: 'fontawesome' },
  { name: 'FaArchive', component: FaArchive, category: 'Files', keywords: ['storage', 'box'], library: 'fontawesome' },
  { name: 'FaTags', component: FaTags, category: 'Commerce', keywords: ['labels', 'prices'], library: 'fontawesome' },
  { name: 'FaShoppingCart', component: FaShoppingCart, category: 'Commerce', keywords: ['cart', 'buy'], library: 'fontawesome' },
  { name: 'FaCreditCard', component: FaCreditCard, category: 'Commerce', keywords: ['payment', 'card'], library: 'fontawesome' },
  { name: 'FaDollarSign', component: FaDollarSign, category: 'Commerce', keywords: ['money', 'price'], library: 'fontawesome' },
  { name: 'FaChartLine', component: FaChartLine, category: 'Commerce', keywords: ['graph', 'trend'], library: 'fontawesome' },
  { name: 'FaChartBar', component: FaChartBar, category: 'Commerce', keywords: ['graph', 'analytics'], library: 'fontawesome' },
  { name: 'FaChartPie', component: FaChartPie, category: 'Commerce', keywords: ['graph', 'donut'], library: 'fontawesome' },
  { name: 'FaChartArea', component: FaChartArea, category: 'Commerce', keywords: ['graph', 'area'], library: 'fontawesome' },
  { name: 'FaBullseye', component: FaBullseye, category: 'Commerce', keywords: ['target', 'goal'], library: 'fontawesome' },
  { name: 'FaTrophy', component: FaTrophy, category: 'Social', keywords: ['winner', 'champion'], library: 'fontawesome' },
  { name: 'FaMedal', component: FaMedal, category: 'Social', keywords: ['prize', 'achievement'], library: 'fontawesome' },
  { name: 'FaFire', component: FaFire, category: 'Social', keywords: ['trending', 'hot', 'flame'], library: 'fontawesome' },
  { name: 'FaSun', component: FaSun, category: 'Shapes', keywords: ['light', 'day', 'bright'], library: 'fontawesome' },
  { name: 'FaMoon', component: FaMoon, category: 'Shapes', keywords: ['dark', 'night', 'theme'], library: 'fontawesome' },
  { name: 'FaCloud', component: FaCloud, category: 'Device', keywords: ['storage', 'server'], library: 'fontawesome' },
  { name: 'FaCloudRain', component: FaCloudRain, category: 'Device', keywords: ['weather', 'rain'], library: 'fontawesome' },
  { name: 'FaSnowflake', component: FaSnowflake, category: 'Shapes', keywords: ['winter', 'cold'], library: 'fontawesome' },
  { name: 'FaWind', component: FaWind, category: 'Device', keywords: ['air', 'breeze'], library: 'fontawesome' },
  { name: 'FaMap', component: FaMap, category: 'Maps', keywords: ['location', 'navigation'], library: 'fontawesome' },
  { name: 'FaLocationArrow', component: FaLocationArrow, category: 'Maps', keywords: ['compass', 'direction'], library: 'fontawesome' },
  { name: 'FaCompass', component: FaCompass, category: 'Maps', keywords: ['direction', 'navigation'], library: 'fontawesome' },
  { name: 'FaAnchor', component: FaAnchor, category: 'Maps', keywords: ['ship', 'port'], library: 'fontawesome' },
  { name: 'FaTruck', component: FaTruck, category: 'Commerce', keywords: ['delivery', 'transport'], library: 'fontawesome' },
  { name: 'FaShip', component: FaShip, category: 'Maps', keywords: ['boat', 'marine'], library: 'fontawesome' },
  { name: 'FaPlane', component: FaPlane, category: 'Maps', keywords: ['airplane', 'travel'], library: 'fontawesome' },
  { name: 'FaBicycle', component: FaBicycle, category: 'Maps', keywords: ['bike', 'cycle'], library: 'fontawesome' },
  { name: 'FaDumbbell', component: FaDumbbell, category: 'Social', keywords: ['gym', 'fitness'], library: 'fontawesome' },
  { name: 'FaBolt', component: FaBolt, category: 'Actions', keywords: ['lightning', 'fast', 'energy'], library: 'fontawesome' },
  { name: 'FaPaw', component: FaPaw, category: 'Social', keywords: ['animal', 'pet'], library: 'fontawesome' },
  { name: 'FaUtensils', component: FaUtensils, category: 'Social', keywords: ['food', 'restaurant', 'dining'], library: 'fontawesome' },
  { name: 'FaBed', component: FaBed, category: 'Social', keywords: ['hotel', 'sleep'], library: 'fontawesome' },
  { name: 'FaHospital', component: FaHospital, category: 'Social', keywords: ['medical', 'health'], library: 'fontawesome' },
  { name: 'FaGraduationCap', component: FaGraduationCap, category: 'Social', keywords: ['education', 'school'], library: 'fontawesome' },
  { name: 'FaStore', component: FaStore, category: 'Commerce', keywords: ['shop', 'retail'], library: 'fontawesome' },
  { name: 'FaBuilding', component: FaBuilding, category: 'Commerce', keywords: ['office', 'company'], library: 'fontawesome' },
  { name: 'FaBriefcase', component: FaBriefcase, category: 'Commerce', keywords: ['work', 'job'], library: 'fontawesome' },
  { name: 'FaMoneyBillWave', component: FaMoneyBillWave, category: 'Commerce', keywords: ['money', 'cash'], library: 'fontawesome' },
  { name: 'FaReceipt', component: FaReceipt, category: 'Commerce', keywords: ['bill', 'invoice'], library: 'fontawesome' },
  { name: 'FaGift', component: FaGift, category: 'Commerce', keywords: ['present', 'surprise'], library: 'fontawesome' },
  { name: 'FaTag', component: FaTag, category: 'Commerce', keywords: ['label', 'price'], library: 'fontawesome' },
  { name: 'FaPalette', component: FaPalette, category: 'Media', keywords: ['color', 'paint'], library: 'fontawesome' },
  { name: 'FaPaintBrush', component: FaPaintBrush, category: 'Media', keywords: ['art', 'draw'], library: 'fontawesome' },
  { name: 'FaPen', component: FaPen, category: 'Actions', keywords: ['write', 'edit'], library: 'fontawesome' },
  { name: 'FaFont', component: FaFont, category: 'Media', keywords: ['text', 'font'], library: 'fontawesome' },
  { name: 'FaBold', component: FaBold, category: 'Media', keywords: ['text', 'strong'], library: 'fontawesome' },
  { name: 'FaItalic', component: FaItalic, category: 'Media', keywords: ['text', 'emphasis'], library: 'fontawesome' },
  { name: 'FaUnderline', component: FaUnderline, category: 'Media', keywords: ['text', 'underline'], library: 'fontawesome' },
  { name: 'FaAlignLeft', component: FaAlignLeft, category: 'Media', keywords: ['text', 'left'], library: 'fontawesome' },
  { name: 'FaAlignCenter', component: FaAlignCenter, category: 'Media', keywords: ['text', 'center'], library: 'fontawesome' },
  { name: 'FaAlignRight', component: FaAlignRight, category: 'Media', keywords: ['text', 'right'], library: 'fontawesome' },
  { name: 'FaListUl', component: FaListUl, category: 'Media', keywords: ['list', 'bullets'], library: 'fontawesome' },
  { name: 'FaListOl', component: FaListOl, category: 'Media', keywords: ['list', 'numbers'], library: 'fontawesome' },
  { name: 'FaFacebook', component: FaFacebook, category: 'Social', keywords: ['social', 'network'], library: 'fontawesome' },
  { name: 'FaTwitter', component: FaTwitter, category: 'Social', keywords: ['social', 'network'], library: 'fontawesome' },
  { name: 'FaInstagram', component: FaInstagram, category: 'Social', keywords: ['social', 'photo'], library: 'fontawesome' },
  { name: 'FaLinkedin', component: FaLinkedin, category: 'Social', keywords: ['social', 'professional'], library: 'fontawesome' },
  { name: 'FaYoutube', component: FaYoutube, category: 'Social', keywords: ['social', 'video'], library: 'fontawesome' },
  { name: 'FaGithub', component: FaGithub, category: 'Social', keywords: ['social', 'code', 'developer'], library: 'fontawesome' },
  { name: 'FaGoogle', component: FaGoogle, category: 'Social', keywords: ['social', 'search'], library: 'fontawesome' },
  { name: 'FaReddit', component: FaReddit, category: 'Social', keywords: ['social', 'community'], library: 'fontawesome' },
  { name: 'FaPinterest', component: FaPinterest, category: 'Social', keywords: ['social', 'images'], library: 'fontawesome' },
  { name: 'FaTelegram', component: FaTelegram, category: 'Communication', keywords: ['social', 'messaging'], library: 'fontawesome' },
  { name: 'FaWhatsapp', component: FaWhatsapp, category: 'Communication', keywords: ['social', 'messaging'], library: 'fontawesome' },
  { name: 'FaDiscord', component: FaDiscord, category: 'Communication', keywords: ['social', 'chat'], library: 'fontawesome' },
  { name: 'FaSlack', component: FaSlack, category: 'Communication', keywords: ['social', 'workspace'], library: 'fontawesome' },
  { name: 'FaTwitch', component: FaTwitch, category: 'Social', keywords: ['streaming', 'gaming'], library: 'fontawesome' },
  { name: 'FaMedium', component: FaMedium, category: 'Social', keywords: ['blog', 'writing'], library: 'fontawesome' },
];

// Combine all and update counts
export const ICON_LIBRARY: IconEntry[] = [...MUI_ICONS, ...LUCIDE_ICONS, ...FA_ICONS];

// Update counts
ICON_LIBRARIES[0].count = MUI_ICONS.length;
ICON_LIBRARIES[1].count = LUCIDE_ICONS.length;
ICON_LIBRARIES[2].count = FA_ICONS.length;
