import type { ElementType } from 'react';
import {
  Dashboard, Palette, TextFields, SpaceBar, Gradient, Layers,
  CropSquare, Animation, Widgets, Visibility, DesktopWindows,
  Search, ShoppingCart, BarChart, Menu, Close, Notifications,
  AccountCircle, Settings, Home, Mail, Phone, Favorite,
  Share, Bookmark, Edit, Delete, Add, Remove, Check,
   Close as CloseIcon, Warning, Info, Error, CheckCircle,
  ArrowForward, ArrowBack, ArrowUpward, ArrowDownward,
  Refresh, Download, Upload, Send, AttachFile, Link,
   Image, Videocam, MusicNote, PlayArrow, Pause, Stop,
   VolumeUp, VolumeOff, Fullscreen, FullscreenExit, ZoomIn,
   ZoomOut, Filter, Sort, CalendarToday, Schedule, Person,
   People, Group, Lock, LockOpen, VpnKey, Shield, Gavel,
   Build, Code, Storage, Cloud, Wifi, Bluetooth,
   LocationOn, Map, Directions, Flight, Train, DirectionsCar,
   Restaurant, Hotel, LocalHospital, School, Store, Business,
   Work, TrendingUp, TrendingDown, AttachMoney, CreditCard,
   AccountBalance, Receipt, Assignment, Note, List,
   ViewModule, ViewQuilt, FormatPaint, Brush, ColorLens,
   FormatBold, FormatItalic, FormatUnderlined,
   FormatListBulleted, FormatListNumbered, FormatAlignLeft,
   FormatAlignCenter, FormatAlignRight, Code as CodeIcon,
   GitHub, Google, Facebook, Twitter, Instagram, LinkedIn,
   YouTube, Pinterest, Reddit, Telegram, WhatsApp, Chat,
   Forum, Comment, Reply, Forward, Inbox, Drafts, Send as SendIcon,
   Delete as DeleteIcon, Archive, Flag, Label, Tag, Star,
   ThumbUp, ThumbDown, Mood, SentimentSatisfied, SentimentDissatisfied,
   LocalOffer, CardGiftcard, Redeem, Loyalty, Inventory,
   ShoppingCart as CartIcon, Category, Tune, ManageAccounts,
   DashboardCustomize, Web, Devices, PhoneAndroid, TabletMac,
   Laptop, Watch, Headphones, CameraAlt, Brush as BrushIcon,
   Palette as PaletteIcon, Construction,
   FitnessCenter,
   SportsEsports,
   MusicNote as MusicIcon,
   FiberManualRecord, MoreVert, MoreHoriz, ExpandMore, ExpandLess,
   ChevronLeft, ChevronRight, FirstPage, LastPage, SkipNext,
   SkipPrevious, FastForward, FastRewind, Replay, Shuffle,
   Repeat, VolumeDown, VolumeMute, Hearing,
   HighQuality, SlowMotionVideo,
   Speed, Timer, AccessTime,
   Update, TrendingFlat, ShowChart, MultilineChart,
   PieChart, DonutLarge, BubbleChart, ScatterPlot, Assessment,
   Timeline, StackedLineChart, BarChart as BarChartIcon,
} from '@mui/icons-material';

export interface IconEntry {
  name: string;
  component: ElementType;
  category: string;
  keywords: string[];
}

export const ICON_CATEGORIES = [
  'Navigation',
  'Actions',
  'Communication',
  'Commerce',
  'Media',
  'Social',
  'Shapes',
  'Files',
  'Device',
  'Maps',
] as const;

export const ICON_LIBRARY: IconEntry[] = [
  // Navigation
  { name: 'Dashboard', component: Dashboard, category: 'Navigation', keywords: ['home', 'main', 'overview'] },
  { name: 'Menu', component: Menu, category: 'Navigation', keywords: ['hamburger', 'nav', 'drawer'] },
  { name: 'Close', component: CloseIcon, category: 'Navigation', keywords: ['dismiss', 'remove', 'cancel'] },
  { name: 'ChevronLeft', component: ChevronLeft, category: 'Navigation', keywords: ['back', 'arrow', 'previous'] },
  { name: 'ChevronRight', component: ChevronRight, category: 'Navigation', keywords: ['forward', 'arrow', 'next'] },
  { name: 'ExpandMore', component: ExpandMore, category: 'Navigation', keywords: ['dropdown', 'accordion', 'down'] },
  { name: 'ExpandLess', component: ExpandLess, category: 'Navigation', keywords: ['collapse', 'up', 'accordion'] },
  { name: 'MoreVert', component: MoreVert, category: 'Navigation', keywords: ['dots', 'options', 'vertical'] },
  { name: 'MoreHoriz', component: MoreHoriz, category: 'Navigation', keywords: ['dots', 'options', 'horizontal'] },
  { name: 'FirstPage', component: FirstPage, category: 'Navigation', keywords: ['start', 'beginning'] },
  { name: 'LastPage', component: LastPage, category: 'Navigation', keywords: ['end', 'finish'] },
  { name: 'ArrowForward', component: ArrowForward, category: 'Navigation', keywords: ['arrow', 'next', 'right'] },
  { name: 'ArrowBack', component: ArrowBack, category: 'Navigation', keywords: ['arrow', 'back', 'left'] },
  { name: 'ArrowUpward', component: ArrowUpward, category: 'Navigation', keywords: ['arrow', 'up'] },
  { name: 'ArrowDownward', component: ArrowDownward, category: 'Navigation', keywords: ['arrow', 'down'] },
  { name: 'Home', component: Home, category: 'Navigation', keywords: ['house', 'main'] },
  { name: 'Search', component: Search, category: 'Navigation', keywords: ['find', 'lookup', 'magnify'] },
  { name: 'Filter', component: Filter, category: 'Navigation', keywords: ['sort', 'refine'] },
  { name: 'Sort', component: Sort, category: 'Navigation', keywords: ['order', 'arrange'] },
  { name: 'Tune', component: Tune, category: 'Navigation', keywords: ['settings', 'adjust', 'sliders'] },
  { name: 'Web', component: Web, category: 'Navigation', keywords: ['internet', 'website', 'globe'] },
  { name: 'Devices', component: Devices, category: 'Navigation', keywords: ['screens', 'responsive'] },

  // Actions
  { name: 'Add', component: Add, category: 'Actions', keywords: ['create', 'new', 'plus'] },
  { name: 'Remove', component: Remove, category: 'Actions', keywords: ['minus', 'subtract'] },
  { name: 'Check', component: Check, category: 'Actions', keywords: ['done', 'complete', 'confirm', 'success'] },
  { name: 'Edit', component: Edit, category: 'Actions', keywords: ['pencil', 'modify', 'write'] },
  { name: 'Delete', component: DeleteIcon, category: 'Actions', keywords: ['trash', 'remove', 'destroy'] },
  { name: 'Refresh', component: Refresh, category: 'Actions', keywords: ['reload', 'sync', 'update'] },
  { name: 'Download', component: Download, category: 'Actions', keywords: ['save', 'export'] },
  { name: 'Upload', component: Upload, category: 'Actions', keywords: ['import', 'send up'] },
  { name: 'Send', component: SendIcon, category: 'Actions', keywords: ['submit', 'paper plane'] },
  { name: 'Share', component: Share, category: 'Actions', keywords: ['forward', 'distribute'] },
  { name: 'Favorite', component: Favorite, category: 'Actions', keywords: ['heart', 'love', 'like'] },
  { name: 'Star', component: Star, category: 'Actions', keywords: ['rating', 'bookmark', 'important'] },
  { name: 'ThumbUp', component: ThumbUp, category: 'Actions', keywords: ['like', 'approve', 'good'] },
  { name: 'ThumbDown', component: ThumbDown, category: 'Actions', keywords: ['dislike', 'reject', 'bad'] },
  { name: 'Bookmark', component: Bookmark, category: 'Actions', keywords: ['save', 'flag'] },
  { name: 'Flag', component: Flag, category: 'Actions', keywords: ['report', 'important'] },
  { name: 'AttachFile', component: AttachFile, category: 'Actions', keywords: ['clip', 'paperclip'] },
  { name: 'Link', component: Link, category: 'Actions', keywords: ['chain', 'url', 'hyperlink'] },
  { name: 'Build', component: Build, category: 'Actions', keywords: ['tools', 'wrench', 'settings'] },
  { name: 'Code', component: CodeIcon, category: 'Actions', keywords: ['developer', 'programming'] },

  // Communication
  { name: 'Mail', component: Mail, category: 'Communication', keywords: ['email', 'envelope', 'message'] },
  { name: 'Chat', component: Chat, category: 'Communication', keywords: ['message', 'bubble', 'conversation'] },
  { name: 'Phone', component: Phone, category: 'Communication', keywords: ['call', 'telephone'] },
  { name: 'Forum', component: Forum, category: 'Communication', keywords: ['discussion', 'community'] },
  { name: 'Comment', component: Comment, category: 'Communication', keywords: ['note', 'remark'] },
  { name: 'Notifications', component: Notifications, category: 'Communication', keywords: ['bell', 'alert', 'alarm'] },
  { name: 'Inbox', component: Inbox, category: 'Communication', keywords: ['mail', 'messages'] },
  { name: 'Drafts', component: Drafts, category: 'Communication', keywords: ['email', 'unsent'] },
  { name: 'Reply', component: Reply, category: 'Communication', keywords: ['respond', 'back'] },
  { name: 'Forward', component: Forward, category: 'Communication', keywords: ['send', 'ahead'] },
  { name: 'Label', component: Label, category: 'Communication', keywords: ['tag', 'badge'] },
  { name: 'Tag', component: Tag, category: 'Communication', keywords: ['label', 'category'] },
  { name: 'LocalOffer', component: LocalOffer, category: 'Communication', keywords: ['price', 'deal', 'sale'] },

  // Commerce
  { name: 'ShoppingCart', component: CartIcon, category: 'Commerce', keywords: ['cart', 'buy', 'purchase'] },
  { name: 'Store', component: Store, category: 'Commerce', keywords: ['shop', 'retail'] },
  { name: 'AttachMoney', component: AttachMoney, category: 'Commerce', keywords: ['dollar', 'price', 'cost'] },
  { name: 'CreditCard', component: CreditCard, category: 'Commerce', keywords: ['payment', 'card', 'pay'] },
  { name: 'AccountBalance', component: AccountBalance, category: 'Commerce', keywords: ['bank', 'finance'] },
  { name: 'Receipt', component: Receipt, category: 'Commerce', keywords: ['bill', 'invoice'] },
  { name: 'TrendingUp', component: TrendingUp, category: 'Commerce', keywords: ['growth', 'increase', 'up'] },
  { name: 'TrendingDown', component: TrendingDown, category: 'Commerce', keywords: ['decline', 'decrease', 'down'] },
  { name: 'Work', component: Work, category: 'Commerce', keywords: ['briefcase', 'job', 'career'] },
  { name: 'Business', component: Business, category: 'Commerce', keywords: ['office', 'building', 'company'] },
  { name: 'Category', component: Category, category: 'Commerce', keywords: ['group', 'type', 'classification'] },
  { name: 'Inventory', component: Inventory, category: 'Commerce', keywords: ['stock', 'warehouse', 'product'] },
  { name: 'Redeem', component: Redeem, category: 'Commerce', keywords: ['gift', 'voucher', 'coupon'] },
  { name: 'CardGiftcard', component: CardGiftcard, category: 'Commerce', keywords: ['gift', 'present'] },
  { name: 'Loyalty', component: Loyalty, category: 'Commerce', keywords: ['points', 'rewards'] },

  // Media
  { name: 'Image', component: Image, category: 'Media', keywords: ['photo', 'picture', 'gallery'] },
  { name: 'Brush', component: BrushIcon, category: 'Media', keywords: ['paint', 'draw', 'art'] },
  { name: 'Palette', component: PaletteIcon, category: 'Media', keywords: ['color', 'paint'] },
  { name: 'ColorLens', component: ColorLens, category: 'Media', keywords: ['color', 'dropper'] },
  { name: 'FormatPaint', component: FormatPaint, category: 'Media', keywords: ['paint', 'bucket', 'fill'] },
  { name: 'CameraAlt', component: CameraAlt, category: 'Media', keywords: ['photo', 'camera', 'picture'] },
  { name: 'PlayArrow', component: PlayArrow, category: 'Media', keywords: ['video', 'start', 'begin'] },
  { name: 'Pause', component: Pause, category: 'Media', keywords: ['video', 'stop', 'hold'] },
  { name: 'Stop', component: Stop, category: 'Media', keywords: ['video', 'end', 'halt'] },
  { name: 'VolumeUp', component: VolumeUp, category: 'Media', keywords: ['sound', 'audio', 'loud'] },
  { name: 'MusicNote', component: MusicIcon, category: 'Media', keywords: ['audio', 'song'] },
  { name: 'SlowMotionVideo', component: SlowMotionVideo, category: 'Media', keywords: ['slow', 'speed'] },
  { name: 'Speed', component: Speed, category: 'Media', keywords: ['fast', 'velocity', 'gauge'] },
  { name: 'HighQuality', component: HighQuality, category: 'Media', keywords: ['hq', 'quality'] },

  // Social
  { name: 'Person', component: Person, category: 'Social', keywords: ['user', 'avatar', 'profile'] },
  { name: 'People', component: People, category: 'Social', keywords: ['users', 'group', 'team'] },
  { name: 'Group', component: Group, category: 'Social', keywords: ['users', 'community'] },
  { name: 'AccountCircle', component: AccountCircle, category: 'Social', keywords: ['avatar', 'profile', 'circle'] },
  { name: 'Mood', component: Mood, category: 'Social', keywords: ['emoji', 'face', 'happy'] },
  { name: 'SentimentSatisfied', component: SentimentSatisfied, category: 'Social', keywords: ['smile', 'face'] },
  { name: 'SentimentDissatisfied', component: SentimentDissatisfied, category: 'Social', keywords: ['sad', 'face'] },

  // Shapes & Status
  { name: 'CheckCircle', component: Check, category: 'Shapes', keywords: ['success', 'done', 'circle'] },
  { name: 'Warning', component: Warning, category: 'Shapes', keywords: ['alert', 'caution', 'triangle'] },
  { name: 'Info', component: Info, category: 'Shapes', keywords: ['information', 'circle', 'help'] },
  { name: 'Error', component: Error, category: 'Shapes', keywords: ['alert', 'danger', 'circle'] },
  { name: 'CropSquare', component: CropSquare, category: 'Shapes', keywords: ['square', 'box', 'frame'] },
  { name: 'FiberManualRecord', component: FiberManualRecord, category: 'Shapes', keywords: ['circle', 'dot', 'point'] },
  { name: 'BubbleChart', component: BubbleChart, category: 'Shapes', keywords: ['circles', 'abstract'] },

  // Files
  { name: 'Assignment', component: Assignment, category: 'Files', keywords: ['task', 'document'] },
  { name: 'Note', component: Note, category: 'Files', keywords: ['memo', 'text'] },
  { name: 'List', component: List, category: 'Files', keywords: ['items', 'rows'] },
  { name: 'Archive', component: Archive, category: 'Files', keywords: ['storage', 'box'] },
  { name: 'Delete', component: Delete, category: 'Files', keywords: ['trash', 'remove'] },

  // Device
  { name: 'PhoneAndroid', component: PhoneAndroid, category: 'Device', keywords: ['mobile', 'smartphone'] },
  { name: 'TabletMac', component: TabletMac, category: 'Device', keywords: ['tablet', 'ipad'] },
  { name: 'Laptop', component: Laptop, category: 'Device', keywords: ['computer', 'notebook'] },
  { name: 'DesktopWindows', component: DesktopWindows, category: 'Device', keywords: ['monitor', 'pc'] },
  { name: 'Watch', component: Watch, category: 'Device', keywords: ['wearable', 'smartwatch'] },
  { name: 'Headphones', component: Headphones, category: 'Device', keywords: ['audio', 'earphones'] },
  { name: 'Wifi', component: Wifi, category: 'Device', keywords: ['internet', 'wireless', 'signal'] },
  { name: 'Bluetooth', component: Bluetooth, category: 'Device', keywords: ['wireless', 'connect'] },
  { name: 'Cloud', component: Cloud, category: 'Device', keywords: ['storage', 'server', 'online'] },

  // Maps & Location
  { name: 'LocationOn', component: LocationOn, category: 'Maps', keywords: ['pin', 'marker', 'map'] },
  { name: 'Map', component: Map, category: 'Maps', keywords: ['location', 'navigation'] },
  { name: 'Directions', component: Directions, category: 'Maps', keywords: ['route', 'navigate'] },
  { name: 'Flight', component: Flight, category: 'Maps', keywords: ['airplane', 'travel'] },
  { name: 'DirectionsCar', component: DirectionsCar, category: 'Maps', keywords: ['car', 'drive', 'vehicle'] },

  // Layout & Design
  { name: 'Widgets', component: Widgets, category: 'Navigation', keywords: ['components', 'blocks'] },
  { name: 'Layers', component: Layers, category: 'Navigation', keywords: ['stack', 'depth'] },
  { name: 'Animation', component: Animation, category: 'Navigation', keywords: ['motion', 'animate'] },
  { name: 'Gradient', component: Gradient, category: 'Navigation', keywords: ['color', 'transition'] },
  { name: 'TextFields', component: TextFields, category: 'Navigation', keywords: ['text', 'type', 'input'] },
  { name: 'SpaceBar', component: SpaceBar, category: 'Navigation', keywords: ['spacing', 'gap'] },
  { name: 'Visibility', component: Visibility, category: 'Navigation', keywords: ['eye', 'show', 'view'] },
  { name: 'Settings', component: Settings, category: 'Actions', keywords: ['gear', 'cog', 'config'] },
  { name: 'ManageAccounts', component: ManageAccounts, category: 'Actions', keywords: ['user', 'settings'] },
  { name: 'DashboardCustomize', component: DashboardCustomize, category: 'Navigation', keywords: ['layout', 'customize'] },
  { name: 'Assessment', component: Assessment, category: 'Commerce', keywords: ['chart', 'analytics', 'report'] },
  { name: 'PieChart', component: PieChart, category: 'Commerce', keywords: ['graph', 'donut', 'data'] },
  { name: 'BarChart', component: BarChartIcon, category: 'Commerce', keywords: ['graph', 'analytics', 'data'] },
  { name: 'ShowChart', component: ShowChart, category: 'Commerce', keywords: ['line', 'graph', 'trend'] },
  { name: 'Timeline', component: Timeline, category: 'Commerce', keywords: ['history', 'progress'] },
  { name: 'CalendarToday', component: CalendarToday, category: 'Navigation', keywords: ['date', 'calendar'] },
  { name: 'Schedule', component: Schedule, category: 'Navigation', keywords: ['time', 'clock'] },
  { name: 'AccessTime', component: AccessTime, category: 'Navigation', keywords: ['clock', 'time'] },
  { name: 'Timer', component: Timer, category: 'Navigation', keywords: ['stopwatch', 'countdown'] },
  { name: 'Lock', component: Lock, category: 'Actions', keywords: ['security', 'private', 'password'] },
  { name: 'LockOpen', component: LockOpen, category: 'Actions', keywords: ['unlock', 'public'] },
  { name: 'VpnKey', component: VpnKey, category: 'Actions', keywords: ['key', 'access'] },
  { name: 'Shield', component: Shield, category: 'Actions', keywords: ['security', 'protect'] },
  { name: 'Gavel', component: Gavel, category: 'Actions', keywords: ['law', 'legal', 'judge'] },
  { name: 'School', component: School, category: 'Social', keywords: ['education', 'university'] },
  { name: 'Restaurant', component: Restaurant, category: 'Social', keywords: ['food', 'dining'] },
  { name: 'FitnessCenter', component: FitnessCenter, category: 'Social', keywords: ['gym', 'exercise'] },
  { name: 'LocalHospital', component: LocalHospital, category: 'Social', keywords: ['medical', 'health'] },
  { name: 'SportsEsports', component: SportsEsports, category: 'Social', keywords: ['gaming', 'game'] },
  { name: 'FormatBold', component: FormatBold, category: 'Media', keywords: ['text', 'bold', 'strong'] },
  { name: 'FormatItalic', component: FormatItalic, category: 'Media', keywords: ['text', 'italic', 'emphasis'] },
  { name: 'FormatUnderlined', component: FormatUnderlined, category: 'Media', keywords: ['text', 'underline'] },
  { name: 'FormatListBulleted', component: FormatListBulleted, category: 'Media', keywords: ['list', 'bullets'] },
  { name: 'FormatListNumbered', component: FormatListNumbered, category: 'Media', keywords: ['list', 'numbers'] },
  { name: 'FormatAlignLeft', component: FormatAlignLeft, category: 'Media', keywords: ['align', 'left'] },
  { name: 'FormatAlignCenter', component: FormatAlignCenter, category: 'Media', keywords: ['align', 'center'] },
  { name: 'FormatAlignRight', component: FormatAlignRight, category: 'Media', keywords: ['align', 'right'] },
  { name: 'Storage', component: Storage, category: 'Device', keywords: ['database', 'server'] },
  { name: 'Construction', component: Construction, category: 'Actions', keywords: ['tools', 'work'] },
  { name: 'TrendingFlat', component: TrendingFlat, category: 'Commerce', keywords: ['neutral', 'steady'] },
  { name: 'MultilineChart', component: MultilineChart, category: 'Commerce', keywords: ['graph', 'lines', 'data'] },
  { name: 'StackedLineChart', component: StackedLineChart, category: 'Commerce', keywords: ['graph', 'area'] },
  { name: 'DonutLarge', component: DonutLarge, category: 'Commerce', keywords: ['donut', 'chart', 'ring'] },
  { name: 'ScatterPlot', component: ScatterPlot, category: 'Commerce', keywords: ['graph', 'dots', 'data'] },
];
