export const designTokens = {
  effect: {
    hardShadow: {
      shadowType: "dropShadow",
      radius: 8,
      color: "#00000052",
      offsetX: 4,
      offsetY: 6,
      spread: 0,
      cssValue: "4px 6px 8px 0 #00000052",
    },
    mediumShadow: {
      shadowType: "dropShadow",
      radius: 6,
      color: "#00000052",
      offsetX: 2,
      offsetY: 4,
      spread: 0,
      cssValue: "2px 4px 6px 0 #00000052",
    },
    softShadow: {
      shadowType: "dropShadow",
      radius: 20,
      color: "#0000001f",
      offsetX: 2,
      offsetY: 2,
      spread: 0,
      cssValue: "2px 2px 20px 0 #0000001f",
    },
  },
  color: {
    primaryKey: "#6750A4",
    secondaryKey: "#625B71",
    tertiaryKey: "#7D5260",
    neutralKey: "#79747E",
    neutralVariantKey: "#CAC4D0",
    errorKey: "#B3261E",
    primary: {
      0: "#000000",
      10: "#21005D",
      20: "#381E72",
      30: "#4F378B",
      40: "#6750A4",
      50: "#7F67BE",
      60: "#9A82DB",
      70: "#B69DF8",
      80: "#D0BCFF",
      90: "#EADDFF",
      95: "#F6EDFF",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    secondary: {
      0: "#000000",
      10: "#1D192B",
      20: "#332D41",
      30: "#4A4458",
      40: "#625B71",
      50: "#7A7289",
      60: "#958DA5",
      70: "#B0A7C0",
      80: "#CCC2DC",
      90: "#E8DEF8",
      95: "#F6EDFF",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    tertiary: {
      0: "#000000",
      10: "#31111D",
      20: "#492532",
      30: "#633B48",
      40: "#7D5260",
      50: "#986977",
      60: "#B58392",
      70: "#D29DAC",
      80: "#EFB8C8",
      90: "#FFD8E4",
      95: "#FFECF1",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    neutral: {
      0: "#000000",
      10: "#1C1B1F",
      20: "#313033",
      30: "#484649",
      40: "#605D62",
      50: "#79747E",
      60: "#938F99",
      70: "#AEA9B4",
      80: "#C9C5D0",
      90: "#E6E1E5",
      95: "#F4EFF4",
      98: "#FEF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    neutralVariant: {
      0: "#000000",
      10: "#1D1A22",
      20: "#322F37",
      30: "#49454F",
      40: "#605D66",
      50: "#79747E",
      60: "#938F99",
      70: "#AEA9B4",
      80: "#CAC4D0",
      90: "#E7E0EC",
      95: "#F5EEFA",
      98: "#FEF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    error: {
      0: "#000000",
      10: "#410E0B",
      20: "#601410",
      30: "#8C1D18",
      40: "#B3261E",
      50: "#DC362E",
      60: "#E46962",
      70: "#EC928E",
      80: "#F2B8B5",
      90: "#F9DEDC",
      95: "#FCEEEE",
      98: "#FFF9F9",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    role: {
      primary: "#6750A4",
      onPrimary: "#FFFFFF",
      primaryContainer: "#EADDFF",
      onPrimaryContainer: "#21005D",
      secondary: "#625B71",
      onSecondary: "#FFFFFF",
      secondaryContainer: "#E8DEF8",
      onSecondaryContainer: "#1D192B",
      tertiary: "#7D5260",
      onTertiary: "#FFFFFF",
      tertiaryContainer: "#FFD8E4",
      onTertiaryContainer: "#31111D",
      surface: "#FFFBFF",
      onSurface: "#1C1B1F",
      outline: "#79747E",
      error: "#B3261E",
      onError: "#FFFFFF",
    },
  },
  spacing: {
    "0": 0,
    "0.5": 1,
    "1": 2,
    "1.5": 3,
    "2": 4,
    "3": 6,
    "4": 8,
    "5": 10,
    "6": 12,
    "8": 16,
    "10": 20,
    "12": 24,
    "16": 32,
  },
  typography: {
    fontFamily: {
      primary: '"Inter", sans-serif',
      secondary: '"Inter", sans-serif',
    },
    displayLarge: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 56,
      fontWeight: 500,
      lineHeight: 64,
      letterSpacing: -0.04,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    displayMedium: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 45,
      fontWeight: 500,
      lineHeight: 52,
      letterSpacing: -0.03,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    displaySmall: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 36,
      fontWeight: 500,
      lineHeight: 44,
      letterSpacing: -0.02,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    headlineLarge: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 32,
      fontWeight: 600,
      lineHeight: 40,
      letterSpacing: 0,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    headlineMedium: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 28,
      fontWeight: 600,
      lineHeight: 36,
      letterSpacing: 0,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    headlineSmall: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 24,
      fontWeight: 600,
      lineHeight: 32,
      letterSpacing: 0,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    titleLarge: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 22,
      fontWeight: 500,
      lineHeight: 28,
      letterSpacing: 0,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    titleMedium: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 16,
      fontWeight: 600,
      lineHeight: 24,
      letterSpacing: 0.01,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    titleSmall: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 20,
      letterSpacing: 0.01,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    bodyLarge: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 24,
      letterSpacing: 0.02,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    bodyMedium: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 20,
      letterSpacing: 0.015,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    bodySmall: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 12,
      fontWeight: 400,
      lineHeight: 16,
      letterSpacing: 0.025,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    labelLarge: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 14,
      fontWeight: 500,
      lineHeight: 20,
      letterSpacing: 0.01,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    labelMedium: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 11,
      fontWeight: 500,
      lineHeight: 16,
      letterSpacing: 0.03,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
    labelSmall: {
      fontFamily: '"Inter", sans-serif',
      fontSize: 11,
      fontWeight: 500,
      lineHeight: 16,
      letterSpacing: 0.03,
      textDecoration: "none",
      fontStyle: "normal",
      fontStretch: "normal",
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: "none",
    },
  },
};

export function applyDesignTokensToElement(element, tokenPath) {
  const keys = tokenPath.split(".");
  let value = designTokens;
  for (const key of keys) {
    value = value?.[key];
  }
  if (typeof value === "string" && value.startsWith("#")) {
    element.style.color = value;
  }
}

export function getColorWithOpacity(hex, opacity) {
  let hexString = hex;
  if (hexString.length === 4) {
    hexString = `#${hexString[1]}${hexString[1]}${hexString[2]}${hexString[2]}${hexString[3]}${hexString[3]}`;
  }
  const r = parseInt(hexString.slice(1, 3), 16);
  const g = parseInt(hexString.slice(3, 5), 16);
  const b = parseInt(hexString.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export function getTypographyStyle(variant) {
  const token = designTokens.typography[variant];
  if (!token) return null;
  return {
    fontFamily: token.fontFamily,
    fontSize: `${token.fontSize}px`,
    fontWeight: token.fontWeight,
    lineHeight: `${token.lineHeight}px`,
    letterSpacing: `${token.letterSpacing}px`,
  };
}

export function getShadow(type) {
  const shadows = {
    hard: designTokens.effect.hardShadow.cssValue,
    medium: designTokens.effect.mediumShadow.cssValue,
    soft: designTokens.effect.softShadow.cssValue,
  };
  return shadows[type] || shadows.medium;
}

export function getSpacing(size) {
  return `${designTokens.spacing[size]}px`;
}
